project:
  type: website

website:
  title: "torch-nets"
#   favicon: 
#   image: 
  navbar:
#     logo: 
    tools:
      - icon: twitter
        href: https://twitter.com/vinyard_m
      - icon: github
        href: https://github.com/torch-nets/
        menu:
          - text: Source Code
            url:  https://github.com/torch-nets/
          - text: Open an issue
            url:  https://github.com/torch-nets/torch-nets/issues/new

  sidebar:
    contents:
      - text: Home
        href: build_source/index.qmd
      - text: Quickstart
        href: build_source/quickstart.qmd
      - text: Installation
        href: build_source/install.qmd
      - section: "API reference"
        href: build_source/api.qmd          
        contents:
          - text: Layer
            href: build_source/layer.qmd      
      
      - section: "Gallery of examples"
        href: build_source/examples.qmd
      - section: "About"
        href: build_source/about.qmd
        contents:
          - text: Development team
            href: build_source/team.qmd

format:
  html:
    theme: simplex
    css: build_source/styles.css
    toc: true

output:
  html_document:
    css: "styles.css"
